-- PHASE 12: FINDORA Tasks & Opportunities Engine

-- 1. Create the master tasks table
CREATE TABLE IF NOT EXISTS public.platform_tasks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_type TEXT NOT NULL CHECK (task_type IN ('price_quote', 'store_visit', 'market_intel', 'customer_assistance')),
    title_en TEXT NOT NULL,
    title_ar TEXT NOT NULL,
    description_en TEXT NOT NULL,
    description_ar TEXT NOT NULL,
    
    -- Targeting constraints
    required_role TEXT CHECK (required_role IN ('field_scout', 'store_insider', 'casual', 'expert')), -- NULL means any
    min_level INTEGER NOT NULL DEFAULT 1 CHECK (min_level BETWEEN 1 AND 5),
    min_trust_score INTEGER NOT NULL DEFAULT 0 CHECK (min_trust_score BETWEEN 0 AND 100),
    
    -- Economics
    base_reward_egp NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    base_reward_points INTEGER NOT NULL DEFAULT 0,
    
    -- Logistics
    location_data JSONB NOT NULL DEFAULT '{}'::jsonb, -- e.g. { "lat": 30.04, "lng": 31.23, "radius_km": 5, "zone": "Maadi" }
    time_limit_minutes INTEGER NOT NULL DEFAULT 60, -- How long they have to finish once claimed
    
    -- State
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'completed', 'cancelled', 'expired')),
    priority INTEGER NOT NULL DEFAULT 0, -- Higher number = shown first
    
    -- Origin
    created_by_customer_id UUID, -- If requested by a real customer
    created_by_staff_id UUID REFERENCES public.staff_members(id), -- If generated by Admin/AI
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for quick discovery feeds
CREATE INDEX IF NOT EXISTS idx_platform_tasks_discovery 
ON public.platform_tasks(status, min_level, min_trust_score, priority DESC) 
WHERE status = 'open';


-- 2. Create the task claims table (Execution state)
CREATE TABLE IF NOT EXISTS public.task_claims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    task_id UUID NOT NULL REFERENCES public.platform_tasks(id) ON DELETE CASCADE,
    contributor_id UUID NOT NULL REFERENCES public.contributors(id) ON DELETE RESTRICT,
    
    status TEXT NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress', 'submitted', 'approved', 'rejected', 'expired')),
    
    -- Workflow
    submission_data JSONB, -- What the user uploaded
    staff_notes TEXT, -- Feedback from reviewer
    
    -- Timestamps
    claimed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    submitted_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    reviewed_by_staff_id UUID REFERENCES public.staff_members(id)
);

-- Partial unique index to enforce the 1-active-task limit
CREATE UNIQUE INDEX IF NOT EXISTS idx_one_active_task 
ON public.task_claims(contributor_id) 
WHERE status = 'in_progress';

-- Index for checking active claims
CREATE INDEX IF NOT EXISTS idx_task_claims_contributor 
ON public.task_claims(contributor_id, status);
